---
- name: Configuration Ansible Controller
  hosts: ansible-lab-controller
  tasks:
    - name: Ensure latest Ansible version
      become: yes
      ansible.builtin.package:
        name:
          - ansible
          - git
        state: latest
- name: Universal host configuration
  hosts: ansible_lab_hosts
  vars:
    ansible_become: true
  roles:
  - role: ansible-hardening
    vars:
      stig_version: rhel7
      security_enable_pwquality_password_set: yes
      security_password_max_lifetime_days: 90

- name: Configure DNS Server
  hosts: ansible-lab-host1
  vars:
    ansible_become: true
  tasks:
  - name: Disable existing DNS
    ansible.builtin.service:
      name: systemd-resolved
      status: stopped
  - name: Install dnsmasq
    ansible.builtin.package:
      name: dnsmasq
      state: latest