---
admin_samba_pw: '{{ vault_admin_samba_pw }}'
admin_un: 'adminUsername'

samba_server_string: 'Ansible Lab File Server'
samba_workgroup: AZLABGROUP
samba_users:
- name: '{{ admin_un }}'
  password: '{{ admin_samba_pw }}'
samba_shares_root: /srv/samba
samba_shares:
- name: samba_share
  comment: 'Only accessible to {{ admin_un }}'
  valid_users: '{{ admin_un }}'
  write_list: '{{ admin_un }}'
  group: '{{ admin_un }}'
  browseable: 'yes'